import os
import pandas as pd
import argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(SCRIPT_DIR, "..", "results")

# Configuration
parser = argparse.ArgumentParser(description="Generate CEURART LaTeX tables from evaluation results.")
parser.add_argument("--results_dir", type=str, default=RESULTS_DIR, 
                    help="Path to the directory containing the 'eval_...' dataset folders.")
parser.add_argument("--output_dir", type=str, default=os.path.join(RESULTS_DIR, "latex_tables"), 
                    help="Where to save the generated .tex files.")
args = parser.parse_args()

EVAL_TRACK_NAMES = [
    "eval_tfu_training_heldout",
    "eval_tfu_validation_gpt5",
    "eval_tfu_validation_qwen",
    "eval_argtumour",
    "eval_tfu_evaluation",
    "eval_averitec",
]

DATASET_DISPLAY_NAMES = {
    "eval_tfu_training_heldout": "TFU Training Arguments (20\% held-out)",
    "eval_tfu_validation_gpt5": "TFU Validation Arguments generated by GPT-5",
    "eval_tfu_validation_qwen": "TFU Validation Arguments generated by Qwen3-8B",
    "eval_argtumour": "ArgTumour Arguments",
    "eval_tfu_evaluation": "TFU Evaluation Arguments",
    "eval_averitec": "AVeriTeC Arguments",
}

# Model mappings
MODEL_FAMILIES = ["BGE-Large", "Instructor-XL", "Qwen3-Embedding-8B"]
MODEL_MAPPING = {}

for fam in MODEL_FAMILIES:
    # GROUP 1: Dense Retrieval (Base + Tuned + Reranking)
    MODEL_MAPPING[f"{fam}_base"] = {"group": 1, "family": fam, "architecture": fam, "strategy": "Zero-Shot"}
    MODEL_MAPPING[f"{fam}_base_reranked"] = {"group": 1, "family": fam, "architecture": fam, "strategy": "Zero-Shot + Reranker"}
    MODEL_MAPPING[f"{fam}_homogeneous"] = {"group": 1, "family": fam, "architecture": fam, "strategy": "Homogeneous"}
    MODEL_MAPPING[f"{fam}_homogeneous_reranked"] = {"group": 1, "family": fam, "architecture": fam, "strategy": "Homogeneous + Reranker"}
    MODEL_MAPPING[f"{fam}_mixed"] = {"group": 1, "family": fam, "architecture": fam, "strategy": "Mixed"}
    MODEL_MAPPING[f"{fam}_mixed_aug"] = {"group": 1, "family": fam, "architecture": fam, "strategy": "Mixed + Aug"}
    
    # GROUP 2: Hybrid Fusion (RSF)
    arch_hybrid = fam 
    MODEL_MAPPING[f"{fam}_mixed_aug_Hybrid_RSF_0.1"] = {"group": 2, "family": fam, "architecture": arch_hybrid, "strategy": "Hybrid ($\\lambda=0.10$)"}
    MODEL_MAPPING[f"{fam}_mixed_aug_Hybrid_RSF_0.15"] = {"group": 2, "family": fam, "architecture": arch_hybrid, "strategy": "Hybrid ($\\lambda=0.15$)"}
    MODEL_MAPPING[f"{fam}_mixed_aug_Hybrid_RSF_0.2"] = {"group": 2, "family": fam, "architecture": arch_hybrid, "strategy": "Hybrid ($\\lambda=0.20$)"}

def generate_latex_tables(df, output_dir):
    print("Generating Comprehensive CEURART LaTeX Tables...")
    
    if 'Instruction_Type' in df.columns:
        df = df[df['Instruction_Type'].str.lower() == 'unseen'].copy()
        
    if 'Intent' in df.columns:
        df['Intent'] = df['Intent'].str.title()
    else:
        df['Intent'] = 'Unknown'

    os.makedirs(output_dir, exist_ok=True)
    datasets = df['Dataset'].unique()
    
    metrics_info = {
        'NDCG@10': {'name': 'NDCG@10', 'higher_better': True},
        'Precision@R': {'name': 'Prec@R', 'higher_better': True},
        'Stance_Error_R': {'name': 'Hard@R', 'higher_better': False},
        'Irrelevant_Correct_Stance_R': {'name': 'Semi@R', 'higher_better': False},
        'Irrelevant_Incorrect_Stance_R': {'name': 'Easy@R', 'higher_better': False}
    }
    metrics = list(metrics_info.keys())
    
    global_caption_text = (
        "The following tables present comprehensive stance retrieval metrics across all evaluated datasets and model families. "
        "Results represent the mean ($\\mu$) and standard deviation ($\\sigma$) across all 30 standardized instructions to account for prompt-level variance. "
        "Hard@R, Semi-Hard@R, and Easy@R denote the proportion of retrieved hard, semi-hard, and easy negatives within the top $R$ results. "
        "The absolute best score (highest for NDCG/Precision, lowest for error rates) is highlighted in \\textbf{bold}, while the best score within each dense/hybrid sub-group is \\underline{underlined}. "
        "Note that all Hybrid Fusion (RSF) strategies operate exclusively over the Mixed + Aug base models.\n\n"
        "\\vspace{2em}\n\n"
    )
    all_tables_lines = [global_caption_text] 
    
    for dataset in datasets:
        for family in MODEL_FAMILIES:
            family_model_keys = [m for m, v in MODEL_MAPPING.items() if v['family'] == family]
            d_df = df[(df['Dataset'] == dataset) & (df['Model'].isin(family_model_keys))]
            
            if d_df.empty: continue
            
            overall_stats = d_df.groupby('Model')[metrics].agg(['mean', 'std']).fillna(0)
            attack_stats = d_df[d_df['Intent'] == 'Attack'].groupby('Model')[metrics].agg(['mean', 'std']).fillna(0)
            support_stats = d_df[d_df['Intent'] == 'Support'].groupby('Model')[metrics].agg(['mean', 'std']).fillna(0)
            
            stats_dict = {'Attack': attack_stats, 'Support': support_stats, 'Overall': overall_stats}
            
            best_map = {}
            for stance in ['Attack', 'Support', 'Overall']:
                best_map[stance] = {}
                for m in metrics:
                    init_val = -1 if metrics_info[m]['higher_better'] else float('inf')
                    best_map[stance][m] = {'global': init_val}
                    
                    for group_id in range(1, 3):
                        best_map[stance][m][group_id] = init_val
                        
            for stance, stats in stats_dict.items():
                for model in stats.index:
                    if model not in MODEL_MAPPING: continue
                    grp = MODEL_MAPPING[model]['group']
                    for m in metrics:
                        mean_val = stats.loc[model, (m, 'mean')]
                        is_higher_better = metrics_info[m]['higher_better']
                        
                        if is_higher_better:
                            if mean_val > best_map[stance][m]['global']: best_map[stance][m]['global'] = mean_val
                            if mean_val > best_map[stance][m][grp]: best_map[stance][m][grp] = mean_val
                        else:
                            if mean_val < best_map[stance][m]['global']: best_map[stance][m]['global'] = mean_val
                            if mean_val < best_map[stance][m][grp]: best_map[stance][m][grp] = mean_val

            def fmt(val, std, is_global_best, is_group_best):
                s_val = f"{val:.3f}\\pm{std:.2f}"
                if is_global_best and is_group_best:
                    return f"$\\underline{{\\mathbf{{{s_val}}}}}$"
                elif is_global_best:
                    return f"$\\mathbf{{{s_val}}}$"
                elif is_group_best:
                    return f"$\\underline{{{s_val}}}$"
                return f"${s_val}$"

            safe_dataset_name = dataset.replace(' ', '_').replace('(', '').replace(')', '').replace('\\%', '').replace('%', '').lower()
            safe_family_name = family.lower().replace('-', '_')
            display_family_name = "Qwen3-Embedding-8B" if family == "Qwen3-8B" else family

            caption = f"Retrieval performance on the \\textbf{{{dataset}}} dataset using \\textbf{{{display_family_name}}}."
            
            lines = [
                "\\begin{table*}[htbp]",
                "\\centering",
                f"\\caption{{{caption}}}",
                f"\\label{{tab:results_{safe_dataset_name}_{safe_family_name}}}",
                "\\renewcommand{\\arraystretch}{1.2}",
                "\\begin{tabular}{l c ccccc}",
                "\\toprule[1.5pt]",
                "\\textbf{Strategy} & \\textbf{Stance} & \\textbf{NDCG@10} & \\textbf{Prec@R} & \\textbf{Hard@R} & \\textbf{Semi@R} & \\textbf{Easy@R} \\\\",
                "\\midrule[1.5pt]"
            ]
            
            first_group_rendered = False
            
            for group_id in range(1, 3):
                group_models = [m for m, v in MODEL_MAPPING.items() if v['group'] == group_id and v['family'] == family and m in overall_stats.index]
                
                if not group_models:
                    continue
                    
                if first_group_rendered:
                    lines.append("\\midrule[1.5pt]")
                
                if group_id == 1:
                    has_reranker = any("Reranked" in m for m in group_models)
                    group_title = "GROUP 1: Dense Retrieval \\& Reranking" if has_reranker else "GROUP 1: Dense Retrieval"
                else:
                    group_title = "GROUP 2: Hybrid Fusion (RSF)"
                    
                lines.append(f"\\multicolumn{{7}}{{l}}{{\\textbf{{{group_title}}}}} \\\\")
                first_group_rendered = True
                
                for m_idx, model in enumerate(group_models):
                    strat = MODEL_MAPPING[model]['strategy']
                    
                    for s_idx, stance in enumerate(['Attack', 'Support', 'Overall']):
                        stats = stats_dict[stance]
                        
                        row_strs = []
                        if model in stats.index:
                            for m in metrics:
                                mean_val = stats.loc[model, (m, 'mean')]
                                std_val = stats.loc[model, (m, 'std')]
                                
                                is_g_best = abs(mean_val - best_map[stance][m]['global']) < 1e-5
                                is_grp_best = abs(mean_val - best_map[stance][m][group_id]) < 1e-5
                                
                                row_strs.append(fmt(mean_val, std_val, is_g_best, is_grp_best))
                        else:
                            row_strs = ["$-$"] * len(metrics)
                            
                        if s_idx == 0:
                            strat_col = f"\\multirow{{3}}{{*}}{{{strat}}}" 
                        else:
                            strat_col = ""
                        
                        metrics_joined = " & ".join(row_strs)
                        lines.append(f"{strat_col} & {stance} & {metrics_joined} \\\\")
                    
                    if m_idx < len(group_models) - 1:
                        lines.append("\\addlinespace[1.5em]")
                        
            lines.append("\\bottomrule[1.5pt]")
            lines.append("\\end{tabular}") 
            lines.append("\\end{table*}")
            
            clean_filename = f"table_{safe_dataset_name}_{safe_family_name}" 
            out_path = os.path.join(output_dir, f"{clean_filename}.tex")
            with open(out_path, 'w') as f:
                f.write("\n".join(lines))
            print(f"  -> Saved LaTeX Table: {out_path}")
            
            all_tables_lines.extend(lines)
            all_tables_lines.append("\n\\vspace{3em}\n")

    if len(all_tables_lines) > 1:
        combined_path = os.path.join(output_dir, "all_tables_combined.tex")
        with open(combined_path, 'w') as f:
            f.write("\n".join(all_tables_lines))
        print(f"  -> Saved Combined Tables File: {combined_path}")

if __name__ == "__main__":
    all_dfs = []
    
    for track_name in EVAL_TRACK_NAMES:
        track_dir = os.path.join(args.results_dir, track_name)
        csv_path = os.path.join(track_dir, "experiment_results.csv")
        
        if not os.path.exists(csv_path):
            print(f"Skipping {track_name}: No data found at {csv_path}")
            continue
            
        try:
            df = pd.read_csv(csv_path)
            # Tag dataset for the global merge using the clean name
            clean_name = DATASET_DISPLAY_NAMES.get(track_name, track_name)
            df['Dataset'] = clean_name
            all_dfs.append(df)
        except Exception as e:
            print(f"Error processing {track_name}: {e}")

    if all_dfs:
        combined_df = pd.concat(all_dfs, ignore_index=True)
        generate_latex_tables(combined_df, args.output_dir)
        print("\nAll LaTeX tables generated successfully!")
    else:
        print("\nNo CSV data found. Check your --results_dir path.")